export enum ACTION {
  SET_PAGES = 'SET_PAGES',
  SET_USER = 'SET_USER',
  SET_SERVICES_CATEGORIES = 'SET_SERVICES_CATEGORIES',
  SET_SERVICES = 'SET_SERVICES',
  SET_INSTAGRAM_PHOTOS = 'SET_INSTAGRAM_PHOTOS',
}
