name: Get photos from instagram
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Get photos from instagram
        run: |
          curl --request GET \
          --url 'https://vetslon.spb.ru/api/getInstagramPhotos' \
